"""esquema inicial: usuarios, lotes_procesamiento, archivos_procesados, resultados_rg90, eventos_auditoria

Revision ID: 23b646faad6d
Revises: 
Create Date: 2026-08-20 16:09:28.006508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23b646faad6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('lotes_procesamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_libro', sa.String(length=10), nullable=False),
    sa.Column('sistema_origen', sa.String(length=20), nullable=False),
    sa.Column('cantidad_comprobantes', sa.Integer(), nullable=False),
    sa.Column('cantidad_saltos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lotes_usuario_created', 'lotes_procesamiento', ['usuario_id', 'created_at'], unique=False)
    op.create_table('archivos_procesados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=30), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_procesamiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=30), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_procesamiento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eventos_accion_timestamp', 'eventos_auditoria', ['accion', 'timestamp'], unique=False)
    op.create_index('ix_eventos_usuario_timestamp', 'eventos_auditoria', ['usuario_id', 'timestamp'], unique=False)
    op.create_table('resultados_rg90',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('archivo_rg90_nombre', sa.String(length=255), nullable=False),
    sa.Column('total_coinciden', sa.Integer(), nullable=False),
    sa.Column('total_no_en_rg90', sa.Integer(), nullable=False),
    sa.Column('total_no_en_libro', sa.Integer(), nullable=False),
    sa.Column('total_saltos', sa.Integer(), nullable=False),
    sa.Column('fecha_comparacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_procesamiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados_rg90')
    op.drop_index('ix_eventos_usuario_timestamp', table_name='eventos_auditoria')
    op.drop_index('ix_eventos_accion_timestamp', table_name='eventos_auditoria')
    op.drop_table('eventos_auditoria')
    op.drop_table('archivos_procesados')
    op.drop_index('ix_lotes_usuario_created', table_name='lotes_procesamiento')
    op.drop_table('lotes_procesamiento')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
